# Generated by Django 2.1.1 on 2018-09-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=30)),
                ('uphone', models.CharField(max_length=11)),
                ('uimg', models.ImageField(upload_to='static/upload/users')),
                ('usex', models.CharField(max_length=6)),
                ('uage', models.CharField(max_length=3)),
                ('uemail', models.CharField(max_length=20)),
                ('uqq', models.CharField(max_length=11)),
                ('uintegral', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
