# Generated by Django 2.1.1 on 2018-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='users',
            name='uintegral',
            field=models.CharField(max_length=8),
        ),
    ]
